{
 "title": "Windows - SQL - DB Prometheus",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "_host", "label": "host", "query": "label_values(collector)" }
  ]
 },
 "panels": [
  {
   "title": "SQL Server - CPU %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "win_perfmon_sql_server_cpu_use", "legendFormat": "Sql Cpu" }
   ]
  },
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "win_wmi_uptime_SystemUpTime" }
   ]
  },
  {
   "title": "Windows processor queue aka load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_processor_queue_processor_queue_aka_load",
     "legendFormat": "queue length"
    }
   ]
  },
  {
   "title": "Windows cpu percent time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_cpu_percent_cpu_time",
     "legendFormat": "cpu pct"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_wmi_disk_size_Size - win_wmi_disk_size_FreeSpace",
     "legendFormat": "{{ Name }} "
    }
   ]
  },
  {
   "title": "Windows memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "win_wmi_memory_installed_kb_TotalVisibleMemorySize - ignoring(alias,host) win_perfmon_memory_available_available_kbytes",
     "legendFormat": "memory_used"
    },
    {
     "expr": "win_wmi_memory_installed_kb_TotalVisibleMemorySize",
     "legendFormat": "memory_total"
    }
   ]
  },
  {
   "title": "Disk E: Average Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_disk_e_avg_queue_length",
     "legendFormat": "Queue Length"
    }
   ]
  },
  {
   "title": "Page File Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "win_perfmon_page_file_usage", "legendFormat": "page file used" }
   ]
  },
  {
   "title": "Disk E: Reads/Writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_disk_e_read_bytes_per_second{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Reads"
    },
    {
     "expr": "win_perfmon_disk_e_write_bytes_per_second{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Disk C: Average Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_disk_c_avg_queue_length",
     "legendFormat": "Queue Length"
    }
   ]
  },
  {
   "title": "SQL Server - Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_memory_used",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "win_perfmon_sql_server_memory_committed_unused",
     "legendFormat": "Committed Unused"
    }
   ]
  },
  {
   "title": "Disk C: Reads/Writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_disk_c_read_bytes_per_second",
     "legendFormat": "Reads"
    },
    {
     "expr": "win_perfmon_disk_c_write_bytes_per_second",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "SQL Server - Database Pages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_database_pages_pages",
     "legendFormat": "Pages Used"
    }
   ]
  },
  {
   "title": "TCP Segments Retransmitted Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_tcp_segmemts_retransmitted_per_sec",
     "legendFormat": "segments per sec"
    }
   ]
  },
  {
   "title": "SQL Server - Network IO Waits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_network_io_waits_waits",
     "legendFormat": "Waits"
    }
   ]
  },
  {
   "title": "SQL Server - Data Files Size - All",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_data_files_all_kb",
     "legendFormat": "kb"
    }
   ]
  },
  {
   "title": "SQL Server - Longest Block",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_longest_block_minutes",
     "legendFormat": "Minutes"
    }
   ]
  },
  {
   "title": "SQL Server - User Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_user_connections_cxns",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "SQL Server - Baseline Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_baseline_duration_last_run_minutes",
     "legendFormat": "Minutes"
    }
   ]
  },
  {
   "title": "SQL Server - Active Parallel Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_active_parallel_threads_threads",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "SQL Server - Days since last backup",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_days_since_last_backup_days"
    }
   ]
  },
  {
   "title": "SQL Server - Longest Query Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "win_perfmon_sql_server_longest_query_time_minutes",
     "legendFormat": "Minutes",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SQL Server - TempDB Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_tempdb_usage_usage",
     "legendFormat": "Percent"
    }
   ]
  }
 ]
}